name: Build e Teste do Projeto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Clonar repositório
      uses: actions/checkout@v4

    - name: 2. Instalar dependências (g++ e SQLite3)
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libsqlite3-dev

    - name: 3. Compilar a aplicação principal
      run: |
        # Compila todos os fontes do projeto principal
            cd trabalho-1
            g++ main.cpp \
            $(find ./src -name "*.cpp") \
            $(find ./libs -name "*.cpp") \
            -I./src \
            -I./libs \
            -o main \
            -lsqlite3 -lpthread -ldl
      # O executável se chamará 'main'

    - name: 4. Compilar os testes
      run: |
        # Compila os fontes de teste junto com os fontes do projeto
            cd trabalho-1
            g++ tests/test_main.cpp \
            $(find ./tests -name "*.cpp") \
            $(find ./src -name "*.cpp") \
            $(find ./libs -name "*.cpp") \
            -I./src \
            -I./libs \
            -I./tests \
            -o tests_exe \
            -lsqlite3 -lpthread -ldl
      # O executável de testes se chamará 'tests_exe'

    - name: 5. Executar testes
      run: |
        # Executa o arquivo gerado no passo anterior
        ./tests_exe
