name: Build Projeto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compilar testes
      run: |
        cd trabalho-1
        g++ tests.cpp \
        $(find ./tests/ -name "*.cpp") \
        $(find ./src/ -name "*.cpp") \
        db/sqlite/sqlite3.c -o tests_exe -lsqlite3 \
        -std=c++17

    - name: Compilar projeto
      run: |
        cd trabalho-1
        g++ main.cpp \
        $(find ./src/ -name "*.cpp") \
        db/sqlite/sqlite3.c -o main -lsqlite3 \
        -std=c++17

    - name: Executar testes
      run: |
        cd trabalho-1
        ./tests_exe
