name: Build Projeto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compilar projeto
      run: |
        cd trabalho-1
        g++ main.cpp \
        $(find ./tests -name "*.cpp") \
        $(find ./src -name "*.cpp") \
        -o main \
        -std=c++17

    - name: Executar testes
      run: |
        cd trabalho-1
        ./main
