name: Build e Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Gerar documentação com Doxygen
      run: |
        doxygen ./doxygen.txt

    - name: Mover documentação para a pasta docs/
      run: |
        rm -rf docs
        mkdir docs
        ls
        cp -r ./trabalho-1/doxygen_docs/html/. ./docs


  deploy_docs:
    runs-on: ubuntu-latest
    needs: build 

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar deploy para GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
