name: CI projeto

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compilar projeto
      run: |
        cd trabalho-1
        g++ main.cpp \
        $(find ./tests -name "*.cpp") \
        $(find ./src/dominios -name "*.cpp") \
        $(find ./src/entidades -name "*.cpp") \
        -o main \
        -std=c++17

    - name: Executar testes
      run: |
        cd trabalho-1
        ./main
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Gerar documentação com Doxygen
      run: |
        cd trabalho-1
        doxygen doxygen.txt

    - name: Deploy da documentação no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../doxygen_docs/html
