name: Deploy Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Gerar documentação com Doxygen
      run: |
        doxygen ./doxygen.txt

    - name: Copiar documentação para a pasta docs/
      run: |
        rm -rf docs
        mkdir docs
        cp -r ./doxygen_docs/html/. ./docs

    - name: Deploy para gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        target_branch: gh-pages
        source_dir: ./docs
        github_token: ${{ secrets.GITHUB_TOKEN }}

